// ─── Exhaustive Nigerian States and Locations / Local Government Areas (LGAs) ──

export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT (Abuja)",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export type NigerianState = (typeof NIGERIAN_STATES)[number];

export const NIGERIAN_LOCATIONS: Record<string, string[]> = {
  "Abia": [
    "Aba North",
    "Aba South",
    "Arochukwu",
    "Bende",
    "Ikwuano",
    "Isiala Ngwa North",
    "Isiala Ngwa South",
    "Isuikwuato",
    "Obi Ngwa",
    "Ohafia",
    "Osisioma Ngwa",
    "Ugwunagbo",
    "Ukwa East",
    "Ukwa West",
    "Umuahia North",
    "Umuahia South",
    "Umu Nneochi",
  ],
  "Adamawa": [
    "Demsa",
    "Fufore",
    "Ganye",
    "Girei",
    "Gombi",
    "Guyuk",
    "Hong",
    "Jada",
    "Lamurde",
    "Madagali",
    "Maiha",
    "Mayo Belwa",
    "Michika",
    "Mubi North",
    "Mubi South",
    "Numan",
    "Shelleng",
    "Song",
    "Toungo",
    "Yola North",
    "Yola South",
  ],
  "Akwa Ibom": [
    "Abak",
    "Eastern Obolo",
    "Eket",
    "Esit Eket",
    "Essien Udim",
    "Etim Ekpo",
    "Etinan",
    "Ibeno",
    "Ibesikpo Asutan",
    "Ibiono Ibom",
    "Ika",
    "Ikono",
    "Ikot Abasi",
    "Ikot Ekpene",
    "Ini",
    "Itu",
    "Mbo",
    "Mkpat Enin",
    "Nsit Atai",
    "Nsit Ibom",
    "Nsit Ubium",
    "Obot Akara",
    "Okobo",
    "Onna",
    "Oron",
    "Oruk Anam",
    "Udung Uko",
    "Ukanafun",
    "Uruan",
    "Urue-Offong/Oruko",
    "Uyo",
  ],
  "Anambra": [
    "Aguata",
    "Anambra East",
    "Anambra West",
    "Anaocha",
    "Awka North",
    "Awka South",
    "Ayamelum",
    "Dunukofia",
    "Ekwusigo",
    "Idemili North",
    "Idemili South",
    "Ihiala",
    "Njikoka",
    "Nnewi North",
    "Nnewi South",
    "Ogbaru",
    "Onitsha North",
    "Onitsha South",
    "Orumba North",
    "Orumba South",
    "Oyi",
  ],
  "Bauchi": [
    "Alkaleri",
    "Bauchi",
    "Bogoro",
    "Damban",
    "Darazo",
    "Dass",
    "Gamawa",
    "Ganjuwa",
    "Giade",
    "Itas/Gadau",
    "Jama'are",
    "Katagum",
    "Kirfi",
    "Misau",
    "Ningi",
    "Shira",
    "Tafawa Balewa",
    "Toro",
    "Warji",
    "Zaki",
  ],
  "Bayelsa": [
    "Brass",
    "Ekeremor",
    "Kolokuma/Opokuma",
    "Nembe",
    "Ogbia",
    "Sagbama",
    "Southern Ijaw",
    "Yenagoa",
  ],
  "Benue": [
    "Ado",
    "Agatu",
    "Apa",
    "Buruku",
    "Gboko",
    "Guma",
    "Gwer East",
    "Gwer West",
    "Katsina-Ala",
    "Konshisha",
    "Kwande",
    "Logo",
    "Makurdi",
    "Obi",
    "Ogbadibo",
    "Ohimini",
    "Oju",
    "Okpokwu",
    "Otukpo",
    "Tarka",
    "Ukum",
    "Ushongo",
    "Vandeikya",
  ],
  "Borno": [
    "Abadam",
    "Askira/Uba",
    "Bama",
    "Bayo",
    "Biu",
    "Chibok",
    "Damboa",
    "Dikwa",
    "Gubio",
    "Guzamala",
    "Gwoza",
    "Hawul",
    "Jere",
    "Kaga",
    "Kala/Balge",
    "Konduga",
    "Kukawa",
    "Kwaya Kusar",
    "Mafa",
    "Magumeri",
    "Maiduguri",
    "Marte",
    "Mobbar",
    "Monguno",
    "Ngala",
    "Nganzai",
    "Shani",
  ],
  "Cross River": [
    "Abi",
    "Akamkpa",
    "Akpabuyo",
    "Bakassi",
    "Bekwarra",
    "Biase",
    "Boki",
    "Calabar Municipal",
    "Calabar South",
    "Etung",
    "Ikom",
    "Obanliku",
    "Obubra",
    "Obudu",
    "Odukpani",
    "Ogoja",
    "Yakuur",
    "Yala",
  ],
  "Delta": [
    "Aniocha North",
    "Aniocha South",
    "Asaba (GRA)",
    "Bomadi",
    "Burutu",
    "Ethiope East",
    "Ethiope West",
    "Ika North East",
    "Ika South",
    "Isoko North",
    "Isoko South",
    "Ndokwa East",
    "Ndokwa West",
    "Okpe",
    "Oshimili North",
    "Oshimili South",
    "Patani",
    "Sapele",
    "Udu",
    "Ughelli North",
    "Ughelli South",
    "Ukwuani",
    "Uvwie (Effurun)",
    "Warri North",
    "Warri South",
    "Warri South West",
  ],
  "Ebonyi": [
    "Abakaliki",
    "Afikpo North",
    "Afikpo South (Edda)",
    "Ebonyi",
    "Ezza North",
    "Ezza South",
    "Ikwo",
    "Ishielu",
    "Ivo",
    "Izzi",
    "Ohaozara",
    "Ohaukwu",
    "Onicha",
  ],
  "Edo": [
    "Akoko-Edo",
    "Benin City (GRA)",
    "Egor",
    "Esan Central",
    "Esan North-East",
    "Esan South-East",
    "Esan West",
    "Etsako Central",
    "Etsako East",
    "Etsako West",
    "Igueben",
    "Ikpoba Okha",
    "Oredo",
    "Orhionmwon",
    "Ovia North-East",
    "Ovia South-West",
    "Owan East",
    "Owan West",
    "Uhunmwonde",
  ],
  "Ekiti": [
    "Ado Ekiti",
    "Efon",
    "Ekiti East",
    "Ekiti South-West",
    "Ekiti West",
    "Emure",
    "Gbonyin",
    "Ido Osi",
    "Ijero",
    "Ikere",
    "Ikole",
    "Ilejemeje",
    "Irepodun/Ifelodun",
    "Ise/Orun",
    "Moba",
    "Oye",
  ],
  "Enugu": [
    "Aninri",
    "Awgu",
    "Enugu East",
    "Enugu North",
    "Enugu South",
    "Ezeagu",
    "Igbo Etiti",
    "Igbo Eze North",
    "Igbo Eze South",
    "Independence Layout (GRA)",
    "Isi Uzo",
    "New Haven / Ogui",
    "Nkanu East",
    "Nkanu West",
    "Nsukka",
    "Oji River",
    "Trans Ekulu",
    "Udenu",
    "Udi",
    "Uzo Uwani",
  ],
  "FCT (Abuja)": [
    "Abaji",
    "Apo / Guzape",
    "Asokoro",
    "Bwari",
    "Central Business District",
    "Dakwo / Lokogoma",
    "Garki 1 & 2",
    "Gudu / Apo",
    "Gwarinpa Estate",
    "Jabi / Utako",
    "Jahi / Mabushi",
    "Kado / Life Camp",
    "Karu / Nyanya",
    "Kubwa / Dutse",
    "Kuje",
    "Kwali",
    "Lugbe / Airport Road",
    "Maitama",
    "Mpape",
    "Wuye / Katampe",
    "Wuse 1 & 2",
  ],
  "Gombe": [
    "Akko",
    "Balanga",
    "Billiri",
    "Dukku",
    "Funakaye",
    "Gombe Town",
    "Kaltungo",
    "Kwami",
    "Nafada",
    "Shongom",
    "Yamaltu/Deba",
  ],
  "Imo": [
    "Aboh Mbaise",
    "Ahiazu Mbaise",
    "Ehime Mbano",
    "Ezinihitte",
    "Ideato North",
    "Ideato South",
    "Ihitte/Uboma",
    "Ikeduru",
    "Isiala Mbano",
    "Isu",
    "Mbaitoli",
    "Ngor Okpala",
    "Njaba",
    "Nkwerre",
    "Nwangele",
    "Obowo",
    "Oguta",
    "Ohaji/Egbema",
    "Okigwe",
    "Onuimo",
    "Orlu",
    "Orsu",
    "Oru East",
    "Oru West",
    "Owerri Municipal",
    "Owerri North",
    "Owerri West",
  ],
  "Jigawa": [
    "Auyo",
    "Babura",
    "Biriniwa",
    "Birnin Kudu",
    "Buji",
    "Dutse",
    "Gagarawa",
    "Garki",
    "Gumel",
    "Guri",
    "Gwaram",
    "Gwiwa",
    "Hadejia",
    "Jahun",
    "Kafin Hausa",
    "Kaugama",
    "Kazaure",
    "Kiri Kasama",
    "Kiyawa",
    "Maigatari",
    "Malam Madori",
    "Miga",
    "Ringim",
    "Roni",
    "Sule Tankarkar",
    "Taura",
    "Yankwashi",
  ],
  "Kaduna": [
    "Barnawa / Narayi",
    "Birnin Gwari",
    "Chikun",
    "Giwa",
    "Hayin Banki / Kawo",
    "Igabi",
    "Ikara",
    "Jaba",
    "Jema'a (Kafanchan)",
    "Kachia",
    "Kaduna North (GRA)",
    "Kaduna South",
    "Kagarko",
    "Kajuru",
    "Kaura",
    "Kauru",
    "Kubau",
    "Kudan",
    "Lere",
    "Makarfi",
    "Sabon Gari",
    "Sanga",
    "Soba",
    "Tudun Wada / Rigasa",
    "Zangon Kataf",
    "Zaria",
  ],
  "Kano": [
    "Ajingi",
    "Albasu",
    "Bagwai",
    "Bebeji",
    "Bichi",
    "Bunkure",
    "Dala",
    "Dambatta",
    "Dawakin Kudu",
    "Dawakin Tofa",
    "Doguwa",
    "Fagge",
    "Gabasawa",
    "Garko",
    "Garun Mallam",
    "Gaya",
    "Gezawa",
    "Gwale",
    "Gwarzo",
    "Kabo",
    "Kano Municipal (GRA)",
    "Karaye",
    "Kibiya",
    "Kiru",
    "Kumbotso",
    "Kunchi",
    "Kura",
    "Madobi",
    "Makoda",
    "Minjibir",
    "Nasarawa GRA",
    "Rano",
    "Rimin Gado",
    "Rogo",
    "Shanono",
    "Sumaila",
    "Takai",
    "Tarauni",
    "Tofa",
    "Tsanyawa",
    "Tudun Wada",
    "Ungogo",
    "Warawa",
    "Wudil",
  ],
  "Katsina": [
    "Bakori",
    "Batagarawa",
    "Batsari",
    "Baure",
    "Bindawa",
    "Charanchi",
    "Dandume",
    "Danja",
    "Dan Musa",
    "Daura",
    "Dutsin Ma",
    "Faskari",
    "Funtua",
    "Ingawa",
    "Jibia",
    "Kafur",
    "Kaita",
    "Kankara",
    "Kankia",
    "Katsina Central",
    "Kurfi",
    "Kusada",
    "Mai'Adua",
    "Malumfashi",
    "Mani",
    "Mashi",
    "Matazu",
    "Musawa",
    "Rimi",
    "Sabuwa",
    "Safana",
    "Sandamu",
    "Zango",
  ],
  "Kebbi": [
    "Aleiro",
    "Arewa Dandi",
    "Argungu",
    "Augie",
    "Bagudo",
    "Birnin Kebbi",
    "Bunza",
    "Dandi",
    "Fakai",
    "Gwandu",
    "Jega",
    "Kalgo",
    "Koko/Besse",
    "Maiyama",
    "Ngaski",
    "Sakaba",
    "Shanga",
    "Suru",
    "Danko/Wasagu",
    "Yauri",
    "Zuru",
  ],
  "Kogi": [
    "Adavi",
    "Ajaokuta",
    "Ankpa",
    "Bassa",
    "Dekina",
    "Ibaji",
    "Idah",
    "Igalamela Odolu",
    "Ijumu",
    "Kabba/Bunu",
    "Koton Karfe",
    "Lokoja",
    "Mopa Muro",
    "Ofu",
    "Ogori/Magongo",
    "Okehi",
    "Okene",
    "Olamaboro",
    "Omala",
    "Yagba East",
    "Yagba West",
  ],
  "Kwara": [
    "Asa",
    "Baruten",
    "Edu",
    "Ekiti",
    "GRA / Fate (Ilorin)",
    "Ifelodun",
    "Ilorin East",
    "Ilorin South",
    "Ilorin West",
    "Irepodun",
    "Isin",
    "Kaiama",
    "Moro",
    "Offa",
    "Oke Ero",
    "Oyun",
    "Pategi",
    "Tanke / Unilorin Axis",
  ],
  "Lagos": [
    "Abule Egba / Meiran",
    "Agege / Pen Cinema",
    "Aguda / Itire",
    "Ajao Estate / Mafoluku",
    "Ajegunle / Ajeromi-Ifelodun",
    "Ajido / Aradagun (Badagry)",
    "Akoka / University of Lagos",
    "Alaba International / Ojo",
    "Alapere / Agboyi-Ketu",
    "Alimosho / Egbeda / Idimu",
    "Amuwo-Odofin / Mile 2",
    "Anthony Village / Mende",
    "Apapa Wharf / GRA",
    "Arepo / Isheri North (Axis)",
    "Badore / Langbasa",
    "Bariga / Ilaje",
    "Berger / Ojodu / Omole",
    "Bogije / Lakowe / Eleko",
    "Ebute Metta (East & West)",
    "Epe Town / Mojoda",
    "Festac Town (1st-7th Ave)",
    "Gbagada Phase 1 & 2",
    "Ibeju-Lekki / Dangote Refinery Axis",
    "Idumota / Marina / Lagos Island",
    "Ifako-Ijaiye / Ojokoro",
    "Ijanikin / Otto Awori",
    "Ijede / Egbin (Ikorodu)",
    "Ijesha / Surulere",
    "Ikeja GRA / Allen / Opebi",
    "Ikorodu Central / Agric / Ipakodo",
    "Ikosi / Ketu / Mile 12",
    "Ikoyi (Old & Banana Island)",
    "Ilasamaja / Sadiku",
    "Ilupeju / Industrial Estate",
    "Ipaja / Ayobo / Command",
    "Iru / Victoria Island (Oniru)",
    "Isheri Olofin / Iba",
    "Isolo / Okota / Ago Palace",
    "Iyana Iba / LASU Axis",
    "Iyana Ipaja / Pleasure",
    "Ketu / Alapere / Kosofe",
    "Lagos Island (Broad St / CMS)",
    "Lekki Phase 1 / Admiralty",
    "Lekki Phase 2 / Chevron",
    "Magodo Phase 1 & 2 (Shangisha/Isheri)",
    "Maryland / Mende / Cane Village",
    "Mushin / Palm Avenue",
    "Ogudu GRA / Ori-Oke",
    "Ogba / Wemabod / Oke-Ira",
    "Ojodu / Berger / Yakoyo",
    "Ojota / Ogudu / Toll Gate",
    "Okokomaiko / Shibiri",
    "Onike / Iwaya (Yaba)",
    "Onikan / TBS / Obalende",
    "Oregun / Kudirat Abiola Way",
    "Orile Iganmu / Coker",
    "Oshodi / Bolade / Shogunle",
    "Palmgrove / Obanikoro / Fadeyi",
    "Sangotedo / Monastery / Novare",
    "Somolu / Pedro / Bajulaiye",
    "Surulere / Adeniran Ogunsanya / Bode Thomas",
    "VGC (Victoria Garden City)",
    "Victoria Island (VI / Kofo Abayomi)",
    "Yaba / Sabo / Tejuosho",
  ],
  "Nasarawa": [
    "Akwanga",
    "Awe",
    "Doma",
    "Karu (Mararaba/Nyanya Axis)",
    "Keana",
    "Keffi",
    "Kokona",
    "Lafia Central",
    "Nasarawa",
    "Nasarawa Egon",
    "Obi",
    "Toto",
    "Wamba",
  ],
  "Niger": [
    "Agaie",
    "Agwara",
    "Bida",
    "Borgu",
    "Bosso (Minna)",
    "Chanchaga (Minna GRA)",
    "Edati",
    "Gbako",
    "Gurara",
    "Katcha",
    "Kontagora",
    "Lapai",
    "Lavun",
    "Magama",
    "Mariga",
    "Mashegu",
    "Mokwa",
    "Moya",
    "Paikoro",
    "Rafi",
    "Rijau",
    "Shiroro",
    "Suleja / Madalla",
    "Tafa",
    "Wushishi",
  ],
  "Ogun": [
    "Abeokuta North",
    "Abeokuta South (GRA/Oke-Mosan)",
    "Ado-Odo/Ota (Ota / Bells)",
    "Ag Bara Industrial Estate",
    "Arepo / Magboro (Lagos-Ibadan Exp)",
    "Ewekoro",
    "Ibafo / Asese",
    "Ifo / Arigbajo",
    "Ijebu East",
    "Ijebu North (Ago-Iwoye)",
    "Ijebu North East",
    "Ijebu Ode (GRA)",
    "Ikenne / Remo",
    "Imeko Afon",
    "Ipokia",
    "Mowe / Redemption Camp",
    "Obafemi Owode",
    "Odeda",
    "Odogbolu",
    "Ogun Waterside",
    "Remo North",
    "Sagamu (GRA/Interchange)",
    "Sango Ota",
    "Yewa North (Ilaro)",
    "Yewa South",
  ],
  "Ondo": [
    "Akoko North-East (Ikare)",
    "Akoko North-West",
    "Akoko South-East",
    "Akoko South-West",
    "Akure North",
    "Akure South (Alagbaka GRA)",
    "Ese Odo",
    "Idanre",
    "Ifedore",
    "Ilaje",
    "Ile Oluji/Okeigbo",
    "Irele",
    "Odigbo (Ore)",
    "Okitipupa",
    "Ondo East",
    "Ondo West (Ondo Town)",
    "Ose",
    "Owo",
  ],
  "Osun": [
    "Aiyedaade",
    "Aiyedire",
    "Atakunmosa East",
    "Atakunmosa West",
    "Boluwaduro",
    "Boripe",
    "Ede North",
    "Ede South",
    "Egbedore",
    "Ejigbo",
    "Ife Central (OAU/GRA)",
    "Ife East",
    "Ife North",
    "Ife South",
    "Ifedayo",
    "Ifelodun",
    "Ila",
    "Ilesa East",
    "Ilesa West",
    "Irepodun",
    "Irewole (Ikire)",
    "Isokan",
    "Iwo",
    "Obokun",
    "Odo Otin",
    "Ola Oluwa",
    "Olorunda",
    "Oriade",
    "Orolu",
    "Osogbo (GRA)",
  ],
  "Oyo": [
    "Afijio",
    "Akobo / General Gas",
    "Akinyele / Moniya",
    "Alakia / Iwo Road",
    "Apata / Omi Adio",
    "Atiba",
    "Atisbo",
    "Bodija (Old & New)",
    "Challenge / Ring Road",
    "Dugbe / Mokola",
    "Egbeda",
    "Ibadan North",
    "Ibadan North-East",
    "Ibadan North-West",
    "Ibadan South-East",
    "Ibadan South-West",
    "Ibarapa Central",
    "Ibarapa East",
    "Ibarapa North",
    "Ido / Eleyele",
    "Ierwode / Olorunsogo",
    "Iseyin",
    "Itesiwaju",
    "Iwajowa",
    "Jericho / Agodi GRA",
    "Kajola",
    "Lagelu",
    "Ogbomosho North",
    "Ogbomosho South",
    "Ogo Oluwa",
    "Olorunsogo",
    "Oluyole Estate",
    "Ona Ara",
    "Orelope",
    "Ori Ire",
    "Oyo East",
    "Oyo West (Oyo Town)",
    "Saki East",
    "Saki West",
    "Samonda / Sango",
    "Surulere",
    "UI / Ojoo / Agbowo",
  ],
  "Plateau": [
    "Barkin Ladi",
    "Bassa",
    "Bokkos",
    "Jos East",
    "Jos North (GRA)",
    "Jos South (Bukuru)",
    "Kanam",
    "Kanke",
    "Langtang North",
    "Langtang South",
    "Mangu",
    "Mikang",
    "Pankshin",
    "Qua'an Pan",
    "Rayfield / Anglo Jos",
    "Riyom",
    "Shendam",
    "Wase",
  ],
  "Rivers": [
    "Abua/Odual",
    "Ada George / Wimpey",
    "Agip / Mile 4",
    "Ahoada East",
    "Ahoada West",
    "Airforce Base / Aba Road",
    "Akuku-Toru",
    "Amadi Creek / Abuloma",
    "Andoni",
    "Asari-Toru",
    "Bonny Island",
    "Borokiri / Old Port Harcourt",
    "Choba / UNIPORT Axis",
    "D/Line / Isaac Boro",
    "Degema",
    "Diobu (Mile 1, 2, 3)",
    "Elelenwo / Oil Mill",
    "Eleme / Refinery Axis",
    "Eliozu / Rukpokwu",
    "Emuoha",
    "Etche",
    "Gokana",
    "GRA Phase 1, 2, 3",
    "Igwuruta / Airport Road",
    "Ikwerre",
    "Khana",
    "Nchia / Ogale",
    "Nkpolu / Rumuigbo",
    "Obio/Akpor",
    "Ogba/Egbema/Ndoni",
    "Oginigba / Trans Amadi",
    "Ogu/Bolo",
    "Okrika",
    "Old GRA (Portharcourt)",
    "Omuma",
    "Onne Free Zone",
    "Opobo/Nkoro",
    "Oyigbo",
    "Peter Odili / Woji Axis",
    "Port Harcourt Township",
    "Rumueme / Mile 4",
    "Rumuibekwe / Shell RA",
    "Rumuokoro / Rumuodomaya",
    "Rumuola / Stadium Road",
    "Tai",
    "Woji / YKC Axis",
  ],
  "Sokoto": [
    "Binji",
    "Bodinga",
    "Dange Shuni",
    "Gada",
    "Goronyo",
    "Gudu",
    "Gwadabawa",
    "Illela",
    "Isa",
    "Kebbe",
    "Kware",
    "Rabah",
    "Sabon Birni",
    "Shagari",
    "Silame",
    "Sokoto North (GRA)",
    "Sokoto South",
    "Tambuwal",
    "Tangaza",
    "Tureta",
    "Wamako",
    "Wurno",
    "Yabo",
  ],
  "Taraba": [
    "Ardo Kola",
    "Bali",
    "Donga",
    "Gashaka",
    "Gassol",
    "Ibi",
    "Jalingo Central (GRA)",
    "Karim Lamido",
    "Kurmi",
    "Lau",
    "Sardauna (Mambilla)",
    "Takum",
    "Ussa",
    "Wukari",
    "Yorro",
    "Zing",
  ],
  "Yobe": [
    "Bade (Gashua)",
    "Bursari",
    "Damaturu Central (GRA)",
    "Fika",
    "Fune",
    "Geidam",
    "Gujba",
    "Gulani",
    "Jakusko",
    "Karasuwa",
    "Machina",
    "Nangere",
    "Nguru",
    "Potiskum Central",
    "Tarmuwa",
    "Yunusari",
    "Yusufari",
  ],
  "Zamfara": [
    "Anka",
    "Bakura",
    "Birnin Magaji/Kiyaw",
    "Bukkuyum",
    "Bungudu",
    "Gummi",
    "Gusau Central (GRA)",
    "Kaura Namoda",
    "Maradun",
    "Maru",
    "Shinkafi",
    "Talata Mafara",
    "Tsafe",
    "Zurmi",
  ],
};
